
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agohktlyrcfalfscxikw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2hrdGx5cmNmYWxmc2N4aWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTQ3MjEsImV4cCI6MjA2OTA5MDcyMX0.Gz73OhFrfeEfymNxa4kq0to5xEa5WtTR6N6hBFdaSjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
